# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
addons:
  apt:
    packages:
      - nghttp2
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - nghttpd --verbose --no-tls --padding 0 --hexdump --daemon -d '/' 9000
  - julia -e 'Pkg.clone(pwd()); Pkg.build("HTTP2"); Pkg.test("HTTP2"; coverage=true)'
